config/routes.rb
Rails.application.routes.draw do

  devise_for :users
resources :comments, only: [:edit, :create, :update, :destroy,]
resources :blog_posts
# get 'user_posts' => 'blog_posts#user_posts'
get '/:name' => 'blog_posts#user_posts', as: :user_posts

root 'blog_posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, :blog_entry, presence: true
  validates :title, uniqueness: true, length: {maximum: 140}

  paginates_per 3
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog_post
  belongs_to :user
  validates :comment_entry, :blog_post_id, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord



  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blog_posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  # before_action :correct_user, only: [:edit, :update, :destroy]

  # def correct_user
  #   @post = Post.find_by(id: params[:id])
  #   unless current_user?(@post.user)
  #     redirect_to user_path(current_user)
  #   end
  # end

include ApplicationHelper

  def index
    @blog_posts = BlogPost.all.page(params[:page]) #Collection of all the instances of BlogPost in our database

  end

  def show
    @comment = Comment.new
  end

  def user_posts
  	@user = User.find_by(username: params[:name])
  end

  def edit
    no_access_visitors(current_user, @blog_post)
  end

  def new
    @blog_post = BlogPost.new #Creating a new instance of BlogPost (remember initialize from ruby classes)
  end

  def create
    @blog_post = BlogPost.new(blog_post_params) #method we will set up in a second here. This method will help us allow all of the BlogPost attributes
    respond_to do |format|
      if @blog_post.save #Method from the blogPost class
        	format.html { redirect_to blog_post_url(@blog_post), notice: "Blog Post
    		was created successfully."} #route when BlogPost successfully saved to database
      else
        format.html {render :new} #render to new blog post page when blog post can't be saved to database
      end
    end
  end

  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params) #blog_post.update is from the BlogPost class
        format.html { redirect_to blog_post_url(@blog_post), notice: "Blog post was updated successfully"}
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @blog_post.destroy #Method from the BlogPost class
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: "Your Blog Post was DESTROYEDDDDDDDDDD!!!!!!!!!"}
      # Route to when a blog post is destroyed. I could have set instead also root_url as BlogPost index view is also the root page
    end
  end

  private

    def set_blog_post
        @blog_post = BlogPost.find(params[:id])
    end
    def blog_post_params
      params.require(:blog_post).permit(:title, :blog_entry, :user_id)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :set_comment, only: [:edit, :update, :destroy]

def create
  @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html {redirect_to blog_post_url(id: @comment.blog_post_id),
            notice: "Comment was created successfully!"}
          else
            format.html {redirect_to :back, notice: "Comment failed to post!"}
      end
    end
  end



def update
  respond_to do |format|
    if @comment.update(comment_params)
      format.html {redirect_to blog_post_url(id: @comment.blog_post_id),
        notice: "Comment was updated successfully!"}
      else
        format.html { render :edit}
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html {redirect_to blog_post_url(id: @comment.blog_post_id),
      notice: "Your comment was deleted!"}
      end
    end

  def edit
  end

  private

    def comment_params
      params.require(:comment).permit(:user_id, :comment_entry, :blog_post_id)
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

def no_access_visitors(current_user, post_user)
  unless current_user.id == post_user.user_id
  redirect_to root_url
end
end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with(model: @blog_post, local: true) do |form| %>
<% if @blog_post.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@blog_post.errors.count, "error") %>
      prohibited this blog_post from being saved:
    </h2>
    <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="form-group">
  <%= form.text_field :title, placeholder: "Blog Entry Title", class: "form-control" %>
</div>

<div class="form-group">
  <%= form.hidden_field :user_id, value: current_user.id %>
</div>

<div class="form-group">
  <%= form.text_area :blog_entry, placeholder: "Tell Us Something...", rows: 12, class: "form-control" %>
</div>

<div class="actions">
  <%= form.submit "Submit", class: "btn btn-primary" %>
</div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<br>

<%= link_to "Back", blog_posts_path(@blog_post), class: "btn btn-info" %>

<%= link_to "All Blog Posts", blog_posts_path, class: "btn btn-default" %>

app/views/blog_posts/index.html.erb
<h1>Welcome <%= current_user.username %> </h1>
<h2>Current Blog Post</h2>
<div class="row">
  <% @blog_posts.each do |blog_post| %>
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= blog_post.title %>
      </div>
      <div class="panel-body">
        by
        <em><%= link_to blog_post.user.username, user_posts_path(name: blog_post.user.username) %> </em> <br>
        <p> <i>Created: <%= time_ago_in_words(blog_post.created_at) %> ago </i></p>
        <p><%= blog_post.blog_entry %></p>
      </div>
      <div class="panel-footer">
        <%= link_to "Show", blog_post, class:"btn btn-info" %>
        <% if current_user.id == blog_post.user_id %>
        <%= link_to "Edit", edit_blog_post_path(blog_post), class:"btn btn-warning" %>
        <%= link_to "Destroy", blog_post_path(blog_post), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>
<%end%>
</div>

<%= link_to "New Blog Post", new_blog_post_path, class: "btn btn-success" %>
<%= paginate @blog_posts%>

app/views/blog_posts/new.html.erb
<h1>Create a New Blog Post</h1>

<%= render 'form' %>

<br>

<%= link_to "All Blog Posts", blog_posts_path, class: "btn btn-default" %>

app/views/blog_posts/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= @blog_post.title %>
  </div>
  <div class="panel-body">
    <p><%= @blog_post.user.username %></p>
    <p><%= time_ago_in_words(@blog_post.created_at) %>
      ago</p>
    <p><%= @blog_post.blog_entry %></p>
  </div>
  <div class="panel-footer">
    <% if current_user.id == @blog_post.user_id %>
      <%= link_to "Edit", edit_blog_post_path(@blog_post), class: "btn btn- warning" %>
    <%end %>
    <%= link_to "All Blog Posts", blog_posts_path, class: "btn btn-default" %>

  </div>

  <div class="panel panel-success">
    <div class="panel-heading">
      Make a Comment....
    </div>
    <div class="panel-body">
      <%= render 'comments/form' %>
    </div>
  </div>
  <div class="panel panel-success">
    <div class="panel-heading">
      All Comments...
    </div>
    <div class="panel-body">
      <%= render @comment %>
    </div>
  </div>
</div>

app/views/blog_posts/user_posts.html.erb
<h1>All Posts by <b><%= @user.username %></%></b></h1>

<% @user.blog_posts.each do |blog_post| %>
  <div class="row">
    <div class="col-md-12">
      <div class="well">
        <h3><%= link_to blog_post.title, blog_post %></h3>
        <p><em>posted on <%= blog_post.created_at.strftime("%m/%d/%Y at %l:%M%P") %></em></p>
          <p>
            <%= blog_post.blog_entry.html_safe %>
          </p>
            <p>
              <% if current_user.id == blog_post.user_id %>
              	<%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-warning" %>
                  <%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
              <% end %>
          	</p>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/_comment.html.erb
<% @blog_post.comments.each do |comment| %>
<h4><%= link_to comment.user.username, user_posts_path(name: comment.user.username) %></h4>

<p> <%= time_ago_in_words(comment.created_at) %> ago </p>
<p> <%= comment.comment_entry %> </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |form| %>
<% if @comment.errors.any? %>
  <div class='error_explanation'>
    <h2><%= pluralize(@comment.errors.count, "error") %>
      prohibited this blog post from being saved:
    </h2>
    <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <div class="form-group hidden">
    <%= form.number_field :user_id, value: current_user.id %>
  </div>
  <div class="form-group">
    <%= form.text_area :comment_entry, rows: 4, class: "form-control", placeholder: "Enter comment here...." %>
  </div>
  <div class="form-group hidden">
    <%= form.number_field :blog_post_id, value: @blog_post.id %>
  </div>
  <div class="actions">
    <%= form.submit "Set Comment", class: "btn btn-default" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <a class="navbar-brand" href="#">Brand</a> -->
        <div class="navbar">
          <div class="container-fluid">
            <div class="navbar-header">
              <div class="panda">
                <a class="navbar-brand" href="#">
                  <%= link_to image_tag(image_path('panda.jpg'), :size => "100x100"), root_url %>

                </a>
              </div>
              <ul class="nav navbar-nav">
                <li><%= link_to "All Blog Posts", root_path%></li>
                <li><%= link_to "New Blog Post", new_blog_post_path %></li>
              </div>
            </div>
          </ul>
        </div>

      </div>
      <div class="gravlogo">

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">

              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspop="true" aria-expanded="false"><%= gravatar_tag current_user.username %>
              </div>
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        </ul>

      </div>
    </div>
  </div>
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTalentblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
<%= render 'layouts/navbar' %>
      <div class="container">
        <%= yield %>
      </div>



  </body>
</html>